name: Continuous Integration (CI)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    name: Build & Test Applications
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Met en cache les dépendances npm pour accélérer les futurs builds

      - name: Install Monorepo Dependencies
        run: npm install

      - name: Check Backend Compilation
        run: npm run build:backend

      - name: Check Frontend Build
        run: npm run build:frontend